apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-yaml-and-create-pr
spec:
  params:
    - name: repoUrl
      type: string
      description: URL of the Git repository
    - name: filePath
      type: string
      description: Path to the YAML file in the repository
    - name: imagetag
      type: string
      description: The new ref value to be set
    - name: branchName
      type: string
      description: The name of the new branch to create for the PR
  steps:
    - name: update-and-create-pr
      image: quay.io/dsantama/tekton_poc
      volumeMounts:
        - name: repo-volume
          mountPath: /workspace/repo
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1001030000
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: diego-secrets
              key: GITHUB_TOKEN
      script: |
        # Clone the repository with token authentication
        REPO_URL_WITH_TOKEN=$(echo "$(params.repoUrl)" | sed "s|//|//${GITHUB_TOKEN}@|")
        if ! git clone $REPO_URL_WITH_TOKEN /workspace/repo; then
          echo "Cloning failed"
          exit 1
        fi
        echo "Cloning successful"

        # Navigate to the repository
        cd /workspace/repo
        pwd
        ls -la
        git status

        # Update YAML file
        yq eval '.resourceTemplates[] | select(.name == "aws-vpce-operator-stage-sectors").targets[] | select(.name == "aws-vpce-operator-stage-us-west-2-canary").ref = "$(params.imagetag)"' -i $(params.filePath)
        cat $(params.filePath)

        # Create new branch and commit changes
        git -c user.email="dsantama@redhat.com" -c user.name="MrSantamaria" checkout -b $(params.branchName)
        git -c user.email="dsantama@redhat.com" -c user.name="MrSantamaria" add $(params.filePath)
        git -c user.email="dsantama@redhat.com" -c user.name="MrSantamaria" commit -m "Update ref value for aws-vpce-operator-stage-us-west-2-canary"

        # Set remote URL with token authentication for push
        git remote set-url origin $REPO_URL_WITH_TOKEN

        # Push changes and create a pull request
        git push origin $(params.branchName)
        PR_DATA=$(cat <<EOF
        {
          "title": "Update ref for aws-vpce-operator-stage-us-west-2-canary",
          "head": "$(params.branchName)",
          "base": "main",
          "body": "This PR updates the ref for aws-vpce-operator-stage-us-west-2-canary"
        }
        EOF
        )
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/MrSantamaria/tekton-poc/pulls -d "$PR_DATA"
  volumes:
    - name: repo-volume
      emptyDir: {}
