# Start with the Ubuntu base image
FROM ubuntu:latest

# Update packages and install git, curl, and sudo
RUN apt-get update && \
    apt-get install -y git curl sudo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install yq
RUN curl -L https://github.com/mikefarah/yq/releases/download/v4.9.8/yq_linux_amd64 -o /usr/bin/yq && \
    chmod +x /usr/bin/yq

# Create a new user with specified UID and add it to the sudo group
RUN useradd -u 1001030000 -m myuser && \
    echo "myuser:myuser" | chpasswd && adduser myuser sudo

# Give the user passwordless sudo privileges
RUN echo 'myuser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Set the working directory
WORKDIR /workspace

# Switch to your user
USER 1001030000

# Default command or entrypoint
CMD ["bash"]
