# Start with the Ubuntu base image
FROM ubuntu:latest

# Update packages and install git, curl
RUN apt-get update && \
    apt-get install -y git curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install yq
RUN curl -L https://github.com/mikefarah/yq/releases/download/v4.9.8/yq_linux_amd64 -o /usr/bin/yq && \
    chmod +x /usr/bin/yq

# Create a non-root user with the specified UID and a home directory
RUN useradd -u 1001030000 -m -s /bin/bash myuser

# Change ownership of the /workspace directory
RUN mkdir /workspace && chown -R 1001030000:1001030000 /workspace

# Set the working directory
WORKDIR /workspace

# Switch to your non-root user
USER 1001030000

# Default command or entrypoint
CMD ["bash"]