FROM ubuntu:latest

# Update packages and install git, curl
RUN apt-get update && \
    apt-get install -y git curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install yq
RUN curl -L https://github.com/mikefarah/yq/releases/download/v4.9.8/yq_linux_amd64 -o /usr/bin/yq && \
    chmod +x /usr/bin/yq

WORKDIR /workspace
CMD ["bash"]