apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: poc-pipeline-run-
spec:
  pipelineRef:
    name: poc-progressive-delivery-pipeline
  params:
  # These will be part of the dynamic generation of the pipeline
    - name: operator
      value: "aws-vpce-operator"
    - name: env
      value: "int"
    - name: selectors
      value: "ap-northeast-1,main,!fedramp"
    - name: imagetag
      value: "6cee1df"
    - name: repoUrl
      value: "https://github.com/MrSantamaria/tekton-poc"
    - name: filePath
      value: "poc_saas_avo_progressive_delivery.yml"
    - name: branchName
      # This will have to also be dynamically generated
      value: "update-ref-for-aws-vpce-operator-stage-us-west-2-canary"

#Acceptance Test is failing currently.
#Ref: https://redhat-internal.slack.com/archives/CFJD1NZFT/p1705437963483719