apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: poc-progressive-delivery-pipeline
spec:
  params:
    - name: operator
      type: string
      default: ""
    - name: env
      type: string
      default: ""
    - name: selectors
      type: string
      default: ""
    - name: imagetag
      type: string
      default: ""
    - name: repoUrl
      type: string
      default: ""
    - name: filePath
      type: string
      default: ""
    - name: branchName
      type: string
      default: ""
  tasks:
    #- name: first-task-run-acceptance-test-integration
    #  taskRef:
    #    name: run-acceptance-test
      # These are the parameters that will be passed to the TaskRun
      # For a full solution we will have to generate this file dynamically
    #  params:
        # https://github.com/openshift/aws-vpce-operator/tree/main
    #    - name: operator
    #      value: $(params.operator)
    #    - name: env
    #      value: $(params.env)
    #    - name: selectors
    #      value: $(params.selectors)
    #    - name: imagetag
    #      value: $(params.imagetag)
    - name: update-yaml-and-create-pr-task
      #runAfter: []
        # This job is currently failing but we also don't want to use the runAfter.
        # For now I'll leave it as an empty array since we can come back and adjust it later.
        # - first-task-run-acceptance-test-integration
      taskRef:
        name: update-yaml-and-create-pr
      params:
        - name: repoUrl
          value: $(params.repoUrl)
        - name: filePath
          value: $(params.filePath)
        - name: branchName
          value: $(params.branchName)
        - name: imagetag
          value: $(params.imagetag)
    - name: pr-merge-check
      taskRef:
        name: pr-merge-check
      params:
        - name: prLink
          value: $(tasks.update-yaml-and-create-pr-task.results.prLink)
